name: Release

on:
  create:
    tags:
      - v*

jobs:
  server:
    name: server
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.21.12
        id: go

      - name: Check out branch
        uses: actions/checkout@v2

      - name: 1
        run:  ls /home/runner/go/bin

      - name: Install garble
        run: go install mvdan.cc/garble@latest

      - name: 2
        run: ls /home/runner/go/bin

      - name: Get dependencies
        run: |
          go mod download

      - name: Build On Windows 32
        run: |
          garble build -ldflags "-s -w" -trimpath -o ff/ff_32.exe main.go
        env:
          GOOS: windows
          GOARCH: 386

      - name: zip
        run: |
          zip -r ffnew.zip ff/*

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: ffnew.zip
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
